config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'confirmations'
  }
  root 'visitors#new'

  resource :sidekiq_job_report, only: :show

  resources :visitors
  resources :menus do
    collection do
      delete 'deleteDinner'
    end
  end
  resources :table do
    collection do
      patch 'confirmOrder'
      patch 'closeTable'
    end
  end
  resources :orders do
    collection do
      get 'getReceipt'
      post 'addOrder'
    end
  end

  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
  end

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= ::User.new

    if user.roles[0].name == "admin"
      can :create, ::Dinner
    else
      can :index, ::Dinner
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  has_many :visitors
  belongs_to :table
end

app/models/dinner.rb
class Dinner < ApplicationRecord
  has_many :orders
  validates :name, presence: true
  validates :price, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :visitor
  belongs_to :dinner
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :dinners
  has_many :users
  has_many :tables
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/table.rb
class Table < ApplicationRecord
  has_many :bills
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :async

  has_and_belongs_to_many :roles
  has_many :bills
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  has_many :orders
  belongs_to :bill
end

app/models/visitor_dto.rb
class VisitorDto < ApplicationRecord
  def initialize(nickname: , table_name:)
    @nickname, @table_name = nickname, table_name
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  # before_action :authenticate_user!
  #session[:user_id]
  #
  def index
    #???
    @dinner = Dinner.new
    @dinners = Dinner.where(restaurant_id: "1")
  end

  def show
    @dinner = Dinner.find(params[:id])
  end

  def new
  end

  def create
    @dinner = Dinner.new(dinner_params)
    @dinner.save
    if(@dinner.save)
      redirect_to action: "index"
    else
      render 'new'
    end
  end

  private
  def dinner_params
    params.require(:dinner).permit(:name, :price)
  end

end

app/controllers/table_controller.rb
class TableController < ApplicationController
  before_action :authenticate_user!
  #skip_before_action :verify_authenticity_token

  def index
    @tables = Table.where(restaurant_id: "1")
    @orders = Order.all
  end

  def show
    @tables = Table.where(restaurant_id: "1")
    @current_table = Table.find(params[:id])
    @orders = Order.joins(visitor: [{bill: :table}]).where("table_id=?", params[:id]).where("status=?", "active").where("done=?", "0")
  end

  def confirmOrder
    @id_param = params[:order_id]
    order = Order.find(@id_param)
    order.done = "1"
    order.save
  end

  def closeTable
    @id_param = params[:table_id]
    table = Bill.where("table_id=?", @id_param).where("status=?", "active").first
    table.status = "closed"
    table.save
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/table_helper.rb
module TableHelper
end

app/helpers/visitor_helper.rb
module VisitorHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/helpers/waiter_helper.rb
module WaiterHelper
end

app/views/table/index.html.erb
<%= render "layouts/header" %>

<div class="content-body container">
  <div class="row">
    <div class="column col-12 all-table-column">
      <div class="title-block">
          <div class="menu-title">Столики </div>
      </div>
      <div class="table-list">
        <% @tables.each do |table| %>
          <div class="table-item">
            <%#= link_to  "столик", table_path (table), method: :get %>
              <a href="/table/<%= table.id %>" class="table-link" id=<%= table.id %>>Столик <%= table.name %></a>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/table/show.html.erb
<%= render "layouts/header" %>

<div class="content-body container">
  <div class="row">
    <div class="column col-3 table-column">
      <div class="title-block">
        <div class="menu-title">Столики </div>
      </div>
      <div class="table-list">
        <% @tables.each do |table| %>
          <div class="table-item <% if @current_table.id == table.id %>active-table<% end %>">
            <%#= link_to  "столик", table_path (table), method: :get %>
            <a href="/table/<%= table.id %>" class="table-link" id=<%= table.id %>>Столик <%= table.name %></a>
          </div>
        <% end %>
      </div>
    </div>

    <div class="column col-8 order-waiters-column">
      <div class="title-block">
        <div class="order-title">Замовлення</div>
      </div>
      <div class="order-list">
        <div class="container container-order-list">
          <% unless @orders.any? %>
          Від цього столика нема активних замовлень
          <%  end %>
          <% @orders.each do |order| %>
            <div class="row order-item">
              <div class="col-2 menu-item-count"><%= order.count %>x </div>
              <div class="col-6 menu-item-name"><%= order.dinner.name %></div>
              <div class="col-2 menu-item-count">для <%= order.visitor.nickname %> </div>
              <div class="col-2 small-button menu-item-button">
                <button type="button" class="btn btn-light cancel-menu-item confirm-order-menu-item" id=<%= order.id %>>v<i class="fas fa-band-aid"></i></button>
              </div>
            </div>
          <% end %>

        </div>
        <% if @orders.any? %>
        <button type="button" class="btn btn-light close-table-button" id="<%= @current_table.id %> ">Розрахувати столик</button>
          <% end %>
      </div>
    </div>
  </div>
</div>